default:
  MYSQL_CONFIG:
    HOST: "127.0.0.1"
    PORT: 3306
    USER: "root"
    PASSWORD: "123456"
    POOL_SIZE: 50
    MAX_OVERFLOW: 10

  LOG_CONFIG:
    LOG_LEVEL: "INFO"
    USE_JSON: false

  ENV: "development"
